### PR TITLE
Rob's Xmas present to himself: Hacking on the content resolver

### PR DESCRIPTION
**Pull request by mayhem**
This PR was originally supposed to add one new element to the LB radio support and instead it ended up being a huge PR that adds a pile of new features.

All of this is new code with no real users yet, so please review this lightly, looking for obvious problems. The real testing and debugging is about to start once I get more people using this code.

### CODE REVIEW

**Review by amCap1712 — APPROVED** [review]
Took a quick look, LGTM!

**Comment by massdosage** [comment]
Let me know if there is anything here that would benefit being run over my monster audio collection ;)

Also, should we set up GH to by default tick the box to delete the branch on merge so we don't have dangling branches that are already in `main`?

**Comment by mayhem** [comment]
@massdosage : Yes, please. I would love to know what you think of the period-jams or lb-radio features here. That should be quite fun against your collection, methinks. And yes, let me tick that box.

**Comment by mayhem** [comment]
Branches cleaned up and stray PR opened.

**Pull request merged**
