### PR TITLE
Add support for wma, m4a and ogg vorbis; cleanup

### PR DESCRIPTION
**Pull request by mayhem**
This PR adds support for wma, m4a and ogg vorbis files. It also cleans up:

- More pep8 formatting cleanup
- Improve the format read function to be simpler
- Do not use undefined string, return None instead.
- Make TagUtils into separate functions for easier import.

### CODE REVIEW

**Comment by massdosage** [comment]
Code changes look good, I'll run this branch over my local collection later and if it all works will approve.

**Comment by mayhem** [comment]
I've been running the code on my whole collection and found a number of errors that I've fixed. But it also mixed up with the next set of improvements. Let me see if I can finish those soonish.

**Comment by massdosage** [comment]
OK, I've also found a few "is None" errors etc.

**Review by massdosage — APPROVED** [review]
LGTM. I'm sure we'll find more bugs as we go along but I'm happy to merge this an iterate on that.

**Comment by mayhem** [comment]
Sounds good, thanks for the couple of fixes -- though I think those code fixes were supplanted in the next PR. But, let move on.

**Comment by massdosage** [comment]
Cool, yes, I'll give that other branch a go once you've merged/rebased to double check etc.

**Pull request merged**
