### PR TITLE
Fix cleanup message: --delete doesn't exist -> --remove

### PR DESCRIPTION
**Pull request by zas**

### CODE REVIEW

**Review by mayhem — APPROVED** [review]

**Comment by mayhem** [comment]
Thanks!

**Comment by zas** [comment]
BTW, cleanup --remove doesn't work for me atm, raises exception with `peewee.IntegrityError: FOREIGN KEY constraint failed`.

**Comment by mayhem** [comment]
Can you send me your DB file so I can examine it? Just stash it here: robert@kiss:zas.db :)

**Comment by zas** [comment]
> Can you send me your DB file so I can examine it? Just stash it here: robert@kiss:zas.db :)

I trashed this one, but I'll provide one if I can reproduce the issue.

**Pull request merged**
